namespace Propiedades.Models
{
    public class DetallesPropiedad
    {
        public class PropertyDetalle
        {
            public int IdProperty { get; set; }
            public string IdExternal { get; set; }
            public int IdUser { get; set; }
            public int IdClient { get; set; }
            public int IdType { get; set; }
            public int IdState { get; set; }
            public string WebAddress { get; set; }
            public bool Sale { get; set; }
            public bool Rent { get; set; }
            public bool SeasonalRental { get; set; }
            public string FirstImage { get; set; }
            public string FirstImageUrl { get; set; }
            public decimal PriceSale { get; set; }
            public decimal PriceRent { get; set; }
            public decimal PriceSeasonalRental { get; set; }
            public int IdCurrencySale { get; set; }
            public int IdCurrencyRent { get; set; }
            public int IdCurrencySeasonalRental { get; set; }
            public string Street { get; set; }
            public string Number { get; set; }
            public int Unit { get; set; }
            public string Letter { get; set; }
            public string Phase { get; set; }
            public string Role { get; set; }
            public int IdCondominium { get; set; }
            public int IdBorough { get; set; }
            public int IdSector { get; set; }
            public string CoordinatesLat { get; set; }
            public string CoordinatesLong { get; set; }
            public bool Featured { get; set; }
            public bool OnWeb { get; set; }
            public string Observations { get; set; }
            public string InternalObservations { get; set; }
            public string WayToVisit { get; set; }
            public bool ShowMapOnWeb { get; set; }
            public bool SendCoordinatesToPortals { get; set; }
            public bool MarkAsSale { get; set; }
            public bool MarkAsRent { get; set; }
            public bool Visible { get; set; }
            public string PropertyTitle { get; set; }
            public Currency CurrencySale { get; set; }
            public Currency CurrencyRent { get; set; }
            public Currency CurrencySeasonalRental { get; set; }
            public string PriceSaleFormatted { get; set; }
            public string PriceRentFormatted { get; set; }
            public string PriceSeasonFormatted { get; set; }
            public User User { get; set; }
            public Characteristics Characteristics { get; set; }
            public List<PropertyMedia> PropertyMedia { get; set; }
        }
        public class Currency
        {
            public int IdCurrency { get; set; }
            public string Name { get; set; }
            public string Symbol { get; set; }
        }

        public class User
        {
            public string Name { get; set; }
            public string LastName { get; set; }
            public string MotherLastName { get; set; }
            public string Phone1 { get; set; }
            public string Phone2 { get; set; }
            public string Email { get; set; }
            public string PhotoUrl { get; set; }
            public string Description { get; set; }
            public int IdBranch { get; set; }
            public string FullName { get; set; }
        }

        public class Characteristics
        {
            public string TotalSurface { get; set; }
            public string BuildedSurface { get; set; }
            public int UtildSurface { get; set; }
            public int LandSurface { get; set; }
            public int TerraceSurface { get; set; }
            public int HouseSurface { get; set; }
            public int OfficeSurface { get; set; }
            public int WarehouseSurface { get; set; }
            public int PastedSurface { get; set; }
            public int CultivatedSurface { get; set; }
            public int AdministrationSurface { get; set; }
            public int PlantedSurface { get; set; }
            public int HillsSurface { get; set; }
            public int Hectares { get; set; }
            public int Sheds { get; set; }
            public int FrontMeters { get; set; }
            public int DepthMeters { get; set; }
            public int ShowcaseMeters { get; set; }
            public int HullCoveredSurface { get; set; }
            public int Height { get; set; }
            public int DistanceToAsphalt { get; set; }
            public int FloorStand { get; set; }
            public int Density { get; set; }
            public int Packing { get; set; }
            public int PatronsHouse { get; set; }
            public int WorkersHouse { get; set; }
            public int Suites { get; set; }
            public int Bedrooms { get; set; }
            public int Beds { get; set; }
            public int Bathrooms { get; set; }
            public int LivingRooms { get; set; }
            public int Room { get; set; }
            public int Rooms { get; set; }
            public int Privates { get; set; }
            public int Offices { get; set; }
            public int MeetingRooms { get; set; }
            public int ServicesRooms { get; set; }
            public int BedServices { get; set; }
            public int Floors { get; set; }
            public int Elevators { get; set; }
            public int Parkings { get; set; }
            public int CoveredParkings { get; set; }
            public int UncoveredParkings { get; set; }
            public int ClientParkings { get; set; }
            public int ApartmentsPerFloor { get; set; }
            public int OfficesPerFloor { get; set; }
            public int BathroomsPerFloor { get; set; }
            public int PlatformTrailers { get; set; }
            public int Warehouses { get; set; }
            public int Guests { get; set; }
            public int HullEnvironments { get; set; }
            public int TowerNumber { get; set; }
            public int MinimumStay { get; set; }
            public int ConstructionYear { get; set; }
            public int LocalYears { get; set; }
            public int LocalState { get; set; }
            public bool ServiceRoom { get; set; }
            public bool ServiceBathroom { get; set; }
            public bool Warehouse { get; set; }
            public bool DailyDiningRoom { get; set; }
            public bool FamilyRoom { get; set; }
            public bool Receipts { get; set; }
            public bool Sauna { get; set; }
            public bool Jacuzzi { get; set; }
            public bool Furnished { get; set; }
            public bool PetsAllowed { get; set; }
            public bool Home { get; set; }
            public bool IsInterior { get; set; }
            public bool Regularized { get; set; }
            public bool BBQ { get; set; }
            public bool TennisCourt { get; set; }
            public bool ElectricFence { get; set; }
            public bool CCTV { get; set; }
            public bool ChildishGames { get; set; }
            public bool Pool { get; set; }
            public bool GatePool { get; set; }
            public bool AutomaticGate { get; set; }
            public bool AutomaticWatering { get; set; }
            public bool IrrigationWater { get; set; }
            public bool WaterWell { get; set; }
            public bool Well { get; set; }
            public bool Sign { get; set; }
            public bool Condominium { get; set; }
            public bool KeysInOffice { get; set; }
            public bool Stables { get; set; }
            public bool Alarm { get; set; }
            public bool FireAlarms { get; set; }
            public bool BathroomVisit { get; set; }
            public bool Kitchen { get; set; }
            public bool Laundry { get; set; }
            public bool WalkinCloset { get; set; }
            public bool GameRoom { get; set; }
            public bool Refrigerator { get; set; }
            public bool OutdoorBasketballCourt { get; set; }
            public bool IndoorBasketballCourt { get; set; }
            public bool CableTv { get; set; }
            public bool Gym { get; set; }
            public bool Microwave { get; set; }
            public bool Chimney { get; set; }
            public bool Reception { get; set; }
            public bool OnlyFamilies { get; set; }
            public bool HasSilo { get; set; }
            public bool HasWaterTank { get; set; }
            public bool HasWaterers { get; set; }
            public bool HasTapWater { get; set; }
            public bool HasTelephoneLine { get; set; }
            public bool WheelchairRamp { get; set; }
            public bool HousekeepingService { get; set; }
            public bool VentilationSystem { get; set; }
            public bool ChildrenWelcome { get; set; }
            public bool HasBoiler { get; set; }
            public bool FarmHouse { get; set; }
            public bool BreakfastService { get; set; }
            public bool HasBascule { get; set; }
            public bool HasCutlery { get; set; }
            public bool HasDrainage { get; set; }
            public bool HasElectricGenerator { get; set; }
            public bool HasElectricLight { get; set; }
            public bool HasFarmShed { get; set; }
            public bool HasFarmyard { get; set; }
            public bool HasFittingRoom { get; set; }
            public bool HasForestation { get; set; }
            public bool HasNaturalGas { get; set; }
            public bool HasMills { get; set; }
            public bool HasLobby { get; set; }
            public bool HasGrill { get; set; }
            public bool HasDinningArea { get; set; }
            public bool HasDinningRoom { get; set; }
            public bool HasCloset { get; set; }
            public bool HasBreakfastBar { get; set; }
            public bool HasAttic { get; set; }
            public bool HasBalcony { get; set; }
            public bool HasTerrace { get; set; }
            public bool HasRoofGarden { get; set; }
            public bool HasStudy { get; set; }
            public bool HasSecurity { get; set; }
            public bool HasTv { get; set; }
            public bool HasWashingMachine { get; set; }
            public bool ValetParkingService { get; set; }
            public bool HasBusinessCenter { get; set; }
            public bool HasCinemaHall { get; set; }
            public bool HasCistern { get; set; }
            public bool HasAirConditioning { get; set; }
            public bool HasCommonLaundry { get; set; }
            public bool HasGuestParking { get; set; }
            public bool HasFootballPitch { get; set; }
            public bool HasInternetAccess { get; set; }
            public bool HasPlayground { get; set; }
            public bool HasMultipurposeRoom { get; set; }
            public bool HasOpenSpaces { get; set; }
            public bool HasPaddleCourt { get; set; }
            public bool HasPartyRoom { get; set; }
            public bool HasControlledAccess { get; set; }
            public bool HasMultipleUseCourt { get; set; }
            public bool IsPropertyInAuction { get; set; }
            public bool EndorsementRequired { get; set; }
            public bool SuitableForMortgageLoan { get; set; }
            public bool WithGardener { get; set; }
            public bool WithGatedCommunity { get; set; }
            public bool WithGreenArea { get; set; }
            public bool WithLaundryConnection { get; set; }
            public bool WithSateliteTv { get; set; }
            public bool WithSolarEnergy { get; set; }
            public string Mall { get; set; }
            public string CondUrbanization { get; set; }
            public string Constructability { get; set; }
            public string Equipment { get; set; }
            public string Floor { get; set; }
            public string ContactSchedule { get; set; }
            public string AvailableSince { get; set; }
            public string SecurityType { get; set; }
            public int FloorType { get; set; }
            public int FloorBedrooms { get; set; }
            public int TypeFlatBathrooms { get; set; }
            public int FloorKitchen { get; set; }
            public int FloorDiningRoom { get; set; }
            public int FloorLiving { get; set; }
            public int FloorHallEntrance { get; set; }
            public int HouseStyle { get; set; }
            public int HouseType { get; set; }
            public int DepartmentType { get; set; }
            public int Localtype { get; set; }
            public int PropRecep { get; set; }
            public string Orientation { get; set; }
            public int TypeFurnitureCook { get; set; }
            public int IdIsolation { get; set; }
            public int IdOfficeType { get; set; }
            public int GasType { get; set; }
            public int Thermopanel { get; set; }
            public int TypeHotWater { get; set; }
            public string TypeHeating { get; set; }
            public int KitchenType { get; set; }
            public int ConstructionType { get; set; }
            public int CeilingType { get; set; }
            public int WindowType { get; set; }
            public int Sewerage { get; set; }
            public int WaterType { get; set; }
            public int EnergyType { get; set; }
            public string CoverageType { get; set; }
            public string Disposition { get; set; }
            public int FarmType { get; set; }
            public string GarageAccess { get; set; }
            public string GarageType { get; set; }
            public int CheckIn { get; set; }
            public int CheckOut { get; set; }
            public string TypeOfWarehouse { get; set; }
            public int LandAccess { get; set; }
            public int LotDisposition { get; set; }
            public string LotShape { get; set; }
            public int MaintenanceFeeType { get; set; }
            public string PropertyOwnership { get; set; }
            public bool Yard { get; set; }
            public int CommonExpenses { get; set; }
        }

        public class PropertyMedia
        {
            public int IdPropertyMedia { get; set; }
            public string Name { get; set; }
            public string Url { get; set; }
            public int Order { get; set; }
            public string Type { get; set; }
            public int Visibility { get; set; }
        }
    }
}
